export const TOGGLE_LIST = "TOGGLE_LIST";
export const SET_INDEX = "SET_INDEX";
export const SET_SEARCH_HISTORY = "SET_SEARCH_HISTORY";
export const SET_WATCHLIST = "SET_WATCHLIST";
export const SET_PORTFOLIO = "SET_PORTFOLIO";
export const UPDATE_POSITION_TYPE = "UPDATE_POSITION_TYPE";