export const TOGGLE_LIST = "TOGGLE_LIST";
export const GET_INDEX = "GET_INDEX";
export const GET_SEARCH_HISTORY = "GET_SEARCH_HISTORY";
export const GET_WATCHLIST = "GET_WATCHLIST";
export const GET_PORTFOLIO = "GET_PORTFOLIO";
export const UPDATE_POSITION_TYPE = "UPDATE_POSITION_TYPE";